### PR TITLE
Add support for keyfile authentication

### PR DESCRIPTION
**Pull request by Szeraax**

### CODE REVIEW

**Comment by Szeraax** [comment]
#2

**Comment by PrzemyslawKlys** [comment]
Did you had a chance to test it? I would like to merge it in? We could in theory merge it without testing.

**Comment by Szeraax** [comment]
I've now tested and confirmed that you are able to use the keyfile parameter against a local path as well as a UNC share (had to swap to using ` Resolve-Path $PrivateKey | Select-Object -ExpandProperty ProviderPath` to get the share path without the full `Microsoft.PowerShell.Core\FileSystem::\\server\share\file.key` as the string.

I've tested and confirmed that both Connect-Sftp and Connect-Ssh work with this PR in place. AFAIK, the PR is ready for squash and merge.

**Comment by PrzemyslawKlys** [comment]
Thanks, I merged it. I believe we should also add try/catch to prevent any issues if the wrong path or wrong login/pass happens.

**Pull request merged**
